Install CommanDOS via Install Szmelc Wizard : __INSTALL__
Wget WinGet & Get Wget via WinGet : winget install --id=GNU.Wget && winget install --id=Microsoft.Winget
Setup WSL - Bieda Linux Od buta : wsl --install
More cool shit from NoMoreSoft & SzmelcINC : Start-Process 'https://szmelc.com/'
Customowe menu : Start-Process 'C:\path\to\custom_menu.ps1' -Wait
Exit : exit
